
export type CommandType = 'CREATE_ROOM' | 'DESTROY_ROOM' | 'JOIN_ROOM' | 'LEAVE_ROOM' | 'INVITE' | 'EJECT' | 'USER_REGISTER' | 'PRO_REGISTER' | 'GET_USERS' | 'GET_PROFESIONALS' | 'CHAT_MESSAGE' | 'USER_UNREGISTER' | 'PRO_UNREGISTER' | 'PINGBACK'
